# Task 4

## 4.1 Exercise on Functions

### Task 1
Python program that converts between different units of measurement

In [15]:
def convert_unit(conversion_type, option, value):
    """
    Convert measurement between units.
    conversion_type: 'length', 'weight', or 'volume'
    option: '1' for primary conversion, '2' for reverse conversion
    value: float value to convert
    Returns the converted value.
    """
    if conversion_type == 'length':
        if option == '1':
            return value * 3.28084  # m to ft
        elif option == '2':
            return value / 3.28084  # ft to m
    elif conversion_type == 'weight':
        if option == '1':
            return value * 2.20462  # kg to lbs
        elif option == '2':
            return value / 2.20462  # lbs to kg
    elif conversion_type == 'volume':
        if option == '1':
            return value * 0.264172  # L to gal
        elif option == '2':
            return value / 0.264172  # gal to L
    raise ValueError("Invalid conversion type or option")

try:
    ctype = input("Choose conversion type (length, weight, volume): ").strip().lower()
    print("Options: 1 for primary conversion, 2 for reverse conversion")
    option = input("Choose conversion option: ").strip()
    value = float(input("Enter value to convert: "))
    result = convert_unit(ctype, option, value)
    print("Converted value:", result)
except Exception as e:
    print("Error:", e)

Choose conversion type (length, weight, volume): length
Options: 1 for primary conversion, 2 for reverse conversion
Choose conversion option: 1
Enter value to convert: 1.83
Converted value: 6.0039372


### Task 2
Python program that performs various mathematical operations on a list of numbers

In [23]:
def compute_sum(numbers):
    """Return the sum of numbers."""
    return sum(numbers)

def compute_average(numbers):
    """Return the average of numbers."""
    if not numbers:
        raise ValueError("Empty list")
    return sum(numbers) / len(numbers)

def compute_max(numbers):
    """Return the maximum of numbers."""
    return max(numbers)

def compute_min(numbers):
    """Return the minimum of numbers."""
    return min(numbers)

try:
    op = input("Choose operation (sum, average, max, min): ").strip().lower()
    nums = list(map(float, input("Enter numbers separated by spaces: ").split()))
    if op == 'sum':
        print("Result:", compute_sum(nums))
    elif op == 'average':
        print("Result:", compute_average(nums))
    elif op == 'max':
        print("Result:", compute_max(nums))
    elif op == 'min':
        print("Result:", compute_min(nums))
    else:
        print("Unsupported operation")
except Exception as e:
    print("Error:", e)

Choose operation (sum, average, max, min): sum
Enter numbers separated by spaces: 8 8 4 8
Result: 28.0


## 4.2 Exercise on List Manipulation

In [24]:
def extract_every_other(lst):
    """Return every other element starting from the first."""
    return lst[::2]

def get_sublist(lst, start, end):
    """Return sublist from start to end (inclusive)."""
    return lst[start:end+1]

def reverse_list(lst):
    """Return reversed list using slicing."""
    return lst[::-1]

def remove_first_last(lst):
    """Return list without the first and last elements."""
    return lst[1:-1]

def get_first_n(lst, n):
    """Return the first n elements of the list."""
    return lst[:n]

def get_last_n(lst, n):
    """Return the last n elements of the list."""
    return lst[-n:]

def reverse_skip(lst):
    """
    Return every second element in reverse order starting
    from the second-to-last element.
    """
    return lst[-2::-2]

lst = [1, 2, 3, 4, 5, 6]
print("Every other:", extract_every_other(lst))
print("Sublist (indices 2 to 4):", get_sublist(lst, 2, 4))
print("Reversed:", reverse_list(lst))
print("Without first and last:", remove_first_last(lst))
print("First 3 elements:", get_first_n(lst, 3))
print("Last 2 elements:", get_last_n(lst, 2))
print("Reverse skip:", reverse_skip(lst))

Every other: [1, 3, 5]
Sublist (indices 2 to 4): [3, 4, 5]
Reversed: [6, 5, 4, 3, 2, 1]
Without first and last: [2, 3, 4, 5]
First 3 elements: [1, 2, 3]
Last 2 elements: [5, 6]
Reverse skip: [5, 3, 1]


## 4.3 Exercise on Nested List

In [25]:
def flatten(lst):
    """Flatten a one-level nested list."""
    flat = []
    for item in lst:
        if isinstance(item, list):
            flat.extend(item)
        else:
            flat.append(item)
    return flat

def access_nested_element(lst, indices):
    """Return element from nested list given a list of indices."""
    for idx in indices:
        lst = lst[idx]
    return lst

def sum_nested(lst):
    """Return the sum of all numbers in a nested list (any depth)."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

def remove_element(lst, elem):
    """Remove all occurrences of elem from a nested list."""
    new_lst = []
    for item in lst:
        if isinstance(item, list):
            new_lst.append(remove_element(item, elem))
        elif item != elem:
            new_lst.append(item)
    return new_lst

def find_max(lst):
    """Return the maximum element in a nested list (any depth)."""
    current_max = None
    for item in lst:
        sub_max = find_max(item) if isinstance(item, list) else item
        if current_max is None or sub_max > current_max:
            current_max = sub_max
    return current_max

def count_occurrences(lst, elem):
    """Count the occurrences of elem in a nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

def deep_flatten(lst):
    """Flatten a deeply nested list into a single list."""
    flat = []
    for item in lst:
        if isinstance(item, list):
            flat.extend(deep_flatten(item))
        else:
            flat.append(item)
    return flat

def average_nested(lst):
    """Return the average of all elements in a nested list."""
    def helper(l):
        total, count = 0, 0
        for item in l:
            if isinstance(item, list):
                t, c = helper(item)
                total += t
                count += c
            else:
                total += item
                count += 1
        return total, count
    total, count = helper(lst)
    return total / count if count else 0

print("Flatten:", flatten([[1, 2], [3, 4], [5]]))
print("Access nested element:", access_nested_element([[1,2,3], [4,5,6], [7,8,9]], [1, 2]))
nested = [[1, 2], [3, [4, 5]], 6]
print("Sum of nested list:", sum_nested(nested))
print("Remove element 2:", remove_element([[1, 2], [3, 2], [4, 5]], 2))
print("Maximum in nested list:", find_max(nested))
print("Count occurrences of 2:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
print("Deep flatten:", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
print("Average of nested list:", average_nested([[1, 2], [3, 4], [5, 6]]))

Flatten: [1, 2, 3, 4, 5]
Access nested element: 6
Sum of nested list: 21
Remove element 2: [[1], [3], [4, 5]]
Maximum in nested list: 6
Count occurrences of 2: 3
Deep flatten: [1, 2, 3, 4, 5, 6, 7, 8]
Average of nested list: 3.5


# Task 10

## 10.1 Basic Vector and Matrix Operation with Numpy

### Problem - 1
Array Creation

In [26]:
import numpy as np

# 1. Empty array (2x2)
empty_arr = np.empty((2, 2))
print("Empty array (2x2):\n", empty_arr)

# 2. All ones array (4x2)
ones_arr = np.ones((4, 2))
print("\nOnes array (4x2):\n", ones_arr)

# 3. Array filled with a value (e.g., 7) of shape 3x3
full_arr = np.full((3, 3), 7)
print("\nFull array (3x3, fill=7):\n", full_arr)

# 4. Zeros like a given array
given_arr = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_arr = np.zeros_like(given_arr)
print("\nZeros like given array:\n", zeros_like_arr)

# 5. Ones like a given array
ones_like_arr = np.ones_like(given_arr)
print("\nOnes like given array:\n", ones_like_arr)

# 6. Convert a list to a NumPy array
new_list = [1, 2, 3, 4]
np_arr = np.array(new_list)
print("\nConverted numpy array from list:", np_arr)

Empty array (2x2):
 [[2.84701035e-316 0.00000000e+000]
 [2.86136419e-316 6.56735510e-310]]

Ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array (3x3, fill=7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like given array:
 [[0 0 0]
 [0 0 0]]

Ones like given array:
 [[1 1 1]
 [1 1 1]]

Converted numpy array from list: [1 2 3 4]


### Problem - 2
Array Manipulation: Numerical Ranges and Array indexing

In [27]:
# 1. Array with values 10 to 49
arr_10_49 = np.arange(10, 50)
print("Array 10 to 49:\n", arr_10_49)

# 2. 3x3 matrix with values 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix (0-8):\n", matrix_3x3)

# 3. 3x3 identity matrix
identity_3x3 = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_3x3)

# 4. Random array of size 30 and its mean
rand_arr = np.random.random(30)
print("\nRandom array (size 30):\n", rand_arr)
print("Mean:", rand_arr.mean())

# 5. 10x10 random array; find min and max
rand_10x10 = np.random.random((10, 10))
print("\n10x10 Random Array:\n", rand_10x10)
print("Min:", rand_10x10.min(), "Max:", rand_10x10.max())

# 6. Zero array of size 10; replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1  # 5th element (index 4)
print("\nZero array with 5th element as 1:\n", zero_arr)

# 7. Reverse an array [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:\n", reversed_arr)

# 8. 2D array with 1 on border and 0 inside (example 5x5)
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside:\n", border_arr)

# 9. 8x8 checkerboard pattern
checkerboard = np.indices((8, 8)).sum(axis=0) % 2
print("\n8x8 Checkerboard pattern:\n", checkerboard)

Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix (0-8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array (size 30):
 [0.52551445 0.56171853 0.48877089 0.0546786  0.45255845 0.90269425
 0.19881535 0.10721389 0.93450781 0.8225724  0.50737081 0.11544507
 0.21104065 0.94058305 0.57470515 0.50957298 0.90864313 0.75262877
 0.08472206 0.50276703 0.4351097  0.05396035 0.98775232 0.77993924
 0.74335437 0.78399202 0.06182455 0.53395472 0.65387964 0.44471664]
Mean: 0.5211668961124586

10x10 Random Array:
 [[6.78625733e-01 3.99684224e-01 6.47928213e-01 3.99247482e-01
  3.73164758e-01 7.89078526e-01 8.82690274e-01 6.07101551e-01
  5.06211034e-01 9.43595618e-01]
 [3.59716476e-01 3.93272092e-01 7.39638446e-01 7.31741010e-01
  7.93255293e-01 1.43805759e-02 5.97531667e-01 8.99746365e-01
  3.40238711e-01 5.49697438e-02]
 [8.36408274e-01 4.99095709e-

### Problem - 3
Array Operations

In [28]:
# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add x and y
print("x + y:\n", x + y)

# 2. Subtract y from x
print("\nx - y:\n", x - y)

# 3. Multiply x by 3
print("\nMultiply x by 3:\n", x * 3)

# 4. Square each element of x
print("\nSquare of x:\n", x ** 2)

# 5. Dot products
print("\nDot product of v and w:", np.dot(v, w))
print("Dot product of x and v:\n", np.dot(x, v))
print("Dot product of x and y:\n", np.dot(x, y))

# 6. Concatenate x and y along rows; v and w along columns
concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.vstack((v, w)).T
print("\nConcatenated x and y along rows:\n", concat_xy)
print("Concatenated v and w along columns:\n", concat_vw)

# 7. Concatenate x and v (will error due to shape mismatch)
try:
    np.concatenate((x, v), axis=0)
except Exception as e:
    print("\nError concatenating x and v:", e)
    print("Reason: Incompatible dimensions between a 2x2 array and a 1D array.")

x + y:
 [[ 6  8]
 [10 13]]

x - y:
 [[-4 -4]
 [-4 -3]]

Multiply x by 3:
 [[ 3  6]
 [ 9 15]]

Square of x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenated x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along columns:
 [[ 9 11]
 [10 12]]

Error concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: Incompatible dimensions between a 2x2 array and a 1D array.


### Problem - 4
Matrix Operations

In [29]:
# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("A * A^-1:\n", identity)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)

# 3. Prove (AB).T = B.T * A.T
print("\n(AB).T:\n", np.dot(A, B).T)
print("B.T * A.T:\n", np.dot(B.T, A.T))

# 4. Solve the system:
#    2x - 3y +  z = -1
#     x -  y + 2z = -3
#   3x +  y -  z =  9
coef = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3,  1, -1]])
const = np.array([-1, -3, 9])
solution = np.dot(np.linalg.inv(coef), const)
print("\nSolution of the linear system:", solution)

A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]

(AB).T:
 [[23 51]
 [13 29]]
B.T * A.T:
 [[23 51]
 [13 29]]

Solution of the linear system: [ 2.  1. -2.]


## 10.2 Experiment: How Fast is Numpy

In [31]:
import time

# Setup size for element-wise operations
size = 10**6
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]
np1 = np.arange(size)
np2 = np.arange(size)

# Element-wise Addition
start = time.time()
list_add = [a + b for a, b in zip(list1, list2)]
py_add_time = time.time() - start
start = time.time()
np_add = np1 + np2
np_add_time = time.time() - start
print("Python list addition time:", py_add_time)
print("NumPy array addition time:", np_add_time)

# Element-wise Multiplication
start = time.time()
list_mul = [a * b for a, b in zip(list1, list2)]
py_mul_time = time.time() - start
start = time.time()
np_mul = np1 * np2
np_mul_time = time.time() - start
print("\nPython list multiplication time:", py_mul_time)
print("NumPy array multiplication time:", np_mul_time)

# Dot Product
start = time.time()
py_dot = sum(a * b for a, b in zip(list1, list2))
py_dot_time = time.time() - start
start = time.time()
np_dot = np.dot(np1, np2)
np_dot_time = time.time() - start
print("\nPython list dot product time:", py_dot_time)
print("NumPy array dot product time:", np_dot_time)

# Matrix Multiplication for 1000x1000 matrices
n = 1000
mat1 = [[i + j for j in range(n)] for i in range(n)]
mat2 = [[i - j for j in range(n)] for i in range(n)]

def mat_mult(A, B):
    result = [[0]*n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            s = 0
            for k in range(n):
                s += A[i][k] * B[k][j]
            result[i][j] = s
    return result

start = time.time()
py_mat = mat_mult(mat1, mat2)
py_mat_time = time.time() - start
print("\nPython list matrix multiplication time:", py_mat_time)

np_mat1 = np.array(mat1)
np_mat2 = np.array(mat2)
start = time.time()
np_mat = np.dot(np_mat1, np_mat2)
np_mat_time = time.time() - start
print("NumPy array matrix multiplication time:", np_mat_time)

Python list addition time: 0.1503126621246338
NumPy array addition time: 0.005098104476928711

Python list multiplication time: 0.12803339958190918
NumPy array multiplication time: 0.005730628967285156

Python list dot product time: 0.20149850845336914
NumPy array dot product time: 0.0022749900817871094

Python list matrix multiplication time: 170.77056574821472
NumPy array matrix multiplication time: 2.3835365772247314
